apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: myapp-ns
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: 876724398547.dkr.ecr.ap-southeast-2.amazonaws.com/parasecr:27
        imagePullPolicy: Always
        ports:
          - name: web
            containerPort: 8080
      imagePullSecrets:
          - name: regcred
